from .interpolation_linear import LinearInterpolation,linear_interpolation_coeffs
from .interpolation_cubic import NaturalCubicSpline,natural_cubic_spline_coeffs
from .interpolation_common import get_interp_coeffs